export const ARTISAN_URL = 'https://www.artisan.co/';
export const ARTISAN_URL_PRODUCT = 'https://www.artisan.co/sales-ai';
export const ARTISAN_LOGO = 'https://www.artisan.co/_next/image?url=%2Fassets%2Fartisan-primary-logo.webp&w=64&q=75';
export const ARTISAN_TEXT = 'https://www.artisan.co/_next/image?url=%2Fassets%2Fartisan-text-logo.webp&w=256&q=75';
export const ERROR_MESSAGE = 'Sorry, something went wrong.';
export const ARTISAN_DASHBOARD = 'Go to Artisan Dashboard';
export const ARTISAN_PRODUCT_PAGE = 'Show Previous Messages';
export const TYPE_SOMETHING = 'Type Something...';
export const BOT = "Bot";
export const EMAIL_PLACEHOLDER = "Please enter a valid email to enable the chatbot......";
export const EMAIL_INVALID = "Please enter a valid email id.";
export const CHATBOT_ACTIVATED = "Chatbot activated";
